# Heyyy this is a config file for python
# Comments in here are nice
# Define objects or pertinent info with their name
# Followed by said thing (usually in "quotation marks")
# do note that you'll need to install the ruamel dependency for this config (ruamel.yaml)
# if you don't want to do that, .json works just fine

# Bot token goes here
Token: 

#Prefix that the bot uses for commands
Prefix: 

#Quotes database
Quotes: 
Aliases: 

#Attachments directory
Attachments: 

#Role that is defined as being able to delete quotes (within discord client) if needed
Permissions Role: 

# The uhhh "Playing ___" status of the bot
# {prefix} is a placeholder for the command prefix (it should be "watching" here)
Presence: 

#Reactions for commands.
Emoji: '✅'
EmojiCancel: '❌'

#ID of the text channel that all log messages get sent, if needed
#LC-ID: put your channel id here
#You can do more than one channel, just denote it as the above

#template embed settings if you want the bot to read-out a prompt upon start-up
#Embed Settings:
#  Color:
#    r: 0
#    g: 0
#    b: 0
#  Footer:
#    Text: text goes here
#    Icon URL: 
